---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-test
  namespace: default
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/haraldkoch/argo-test.git
        revision: HEAD
        files:
          - path: apps/**/kustomization.yaml
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: argo-test
      source:
        repoURL: https://github.com/haraldkoch/argo-test.git
        path: '{{ .path.path }}'
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
